03.laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'LoginController@index')->name('login')->middleware('guest');

Route::post('authenticate', 'LoginController@loginForm')->name('Authenticate');
Route::post('logout', 'LoginController@logout')->name('logout');


Route::group(['middleware' => 'auth'], function () {
    Route::get('dashboard', 'Backend\DashboardController@index')->name('dashboard');
    // Route::resource('dashboard', 'Backend\DashboardController');

    Route::resource('users', 'Backend\UsersController');
    Route::get('users/edit/{id}', 'Backend\UsersController@show')->name('edit_users');
    Route::patch('users/update/{id}', 'Backend\UsersController@update')->name('update_users');
    Route::delete('users/destroy/{id}', 'Backend\UsersController@destroy')->name('destroy_users');

    Route::resource('transaction', 'Backend\TransactionController');
    Route::get('transaction/edit/{id}', 'Backend\TransactionController@show')->name('edit_transaction');
    Route::patch('transaction/update/{id}', 'Backend\TransactionController@update')->name('update_transaction');
    Route::delete('transaction/destroy/{id}', 'Backend\TransactionController@destroy')->name('destroy_transaction');


});

03.laravel/app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Helpers\ConvertStatusTransaction;
use App\Http\Controllers\Controller;
use App\Models\Entities\Merchant;
use App\Models\Entities\StatusModel;
use App\Models\Entities\Transaction;
use App\Models\User;
use Auth;
use Carbon\Carbon;
use DB;
use Illuminate\Database\Query\Builder;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Collection;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $users = Auth::user();

        $data['count_amount'] = $this->IDR(Transaction::sum('nominal'));
        $data['avg_amount'] = $this->IDR(Transaction::sum('nominal'));
        $status = StatusModel::all();
        $db_status2_sum = Transaction::select('status', DB::raw('SUM(nominal) as total'))->groupBY('status')->get();
        $db_status2_avg = Transaction::select('status', DB::raw('AVG(nominal) as avg'))->groupBY('status')->get();

        foreach ($status as $stts) {
            $stts->new_name = ConvertStatusTransaction::p_status($stts->name);
            foreach ($db_status2_sum as $item) {
                if ($stts->new_name == $item->status) {
                    $stts['total'] = $this->IDR($item->total);
                }
            }
            foreach ($db_status2_avg as $item) {
                if ($stts->new_name == $item->status) {
                    $stts['avg'] = $this->IDR($item->avg);
                }
            }

        }
        if ($request->ajax()) {

            $date = Carbon::now()->format('Y-m-d');
            $datas = Merchant::select('*')->with('transaction')->whereHas('transaction', function ($q) use ($date) {
                // Query the name field in status table
                $q->where('date_transaction', '=', $date); // '=' is optional
            })->get();
            return DataTables::of($datas)
                ->addIndexColumn()
                ->addColumn('user', function ($datas) {
                    $users = User::all();
                    foreach ($users as $user) {
                        if ($datas['userId'] == $user->id) {
                            $getName = $user->name;
                        }
                    }
                    return $getName;
                })
                ->addColumn('status', function ($datas) {
                    $newStatus = ConvertStatusTransaction::f_status($datas->transaction->status);
                    return $newStatus;
                })
                ->rawColumns(['user'])
                ->make(true);
        }

        return view('backend.dashboard.index', compact('users', 'data', 'status'));
    }

    private function IDR($angka)
    {
        $hasil_rupiah = "IDR " . number_format($angka, 0, ',', '.');
        return $hasil_rupiah;

    }
}

03.laravel/app/Http/Controllers/Backend/TransactionController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Helpers\ConvertStatusTransaction;
use App\Http\Controllers\Controller;
use App\Models\Entities\Merchant;
use App\Models\Entities\Transaction;
use App\Models\Entities\StatusModel;
use Auth;
use DB;
use Exception;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:transaction-list|transaction-create|transaction-edit|transaction-delete', ['only' => ['index', 'create', 'store', 'show', 'edit', 'update', 'destroy']]);
        $this->middleware('permission:transaction-create', ['only' => ['show', 'store']]);
        $this->middleware('permission:transaction-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:transaction-delete', ['only' => ['destroy']]);
    }
    public function index(Request $request)
    {
        //

        // dd($datas);
        if ($request->ajax()) {
            $datas = Merchant::select('*')->with('transaction', 'users')->where('userId', Auth::user()->id)->get();

            return DataTables::of($datas)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {

                    // Update Button
                    $updateButton = "<a href='" . route('edit_transaction', $row->id) . "' target='__blank' class='btn btn-sm btn-info updateUser' ><i class='bi bi-pencil-square'></i></a>";

                    // Delete Button
                    $deleteButton = "<a href='javascript:void(0);' class='btn btn-sm btn-danger deleteUser' onclick='deleteData(" . $row->id . ")'><i class='bi bi-trash'></i></a>";

                    return $updateButton . " " . $deleteButton;
                })
                ->rawColumns(['action'])
                ->make(true);

        }
        return view('backend.transaction.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $status = StatusModel::all();
        // dd($status);
        return view('backend.transaction.create', compact('status'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $nominal = str_replace(".", "", str_replace("Rp. ", "", $request->nominal));
        $status = ConvertStatusTransaction::p_status($request->status);
        // dd($status);
        $this->validate($request, [
            'name' => 'required',
            'address' => 'required',
            'nominal' => 'required',
            'status' => 'required'
        ]);

        DB::beginTransaction();
        try {
            $data = new Merchant;
            $data->name = $request->name;
            $data->alamat = $request->address;
            $data->userId = Auth::user()->id;
            $data->save();

            if ($data) {
                $dataTransaction = new Transaction;
                $dataTransaction->nominal = $nominal;
                $dataTransaction->merchantsId = $data->id;
                $dataTransaction->status = $status;
                $dataTransaction->date_transaction = $request->date;
                $dataTransaction->save();
                // dd($dataTransaction);

                DB::commit();
                return redirect()->route('transaction.index')->with('success', 'Data has been created');

            } else {
                DB::rollBack();

                // echo "error 1";
                return redirect()->route('transaction.create')->with('error', 'Ups Error 1.... Please check your data against!');
            }
        } catch (Exception $e) {
            DB::rollBack();

            // dd("error 2 " . $e);
            return redirect()->route('transaction.create')->with('error', 'Ups Error 2... Please check your data against!');
        } catch (\Illuminate\Database\QueryException $e) {
            DB::rollBack();
            // dd("error 3 " . $e);
            return redirect()->route('transaction.create')->with('error', 'Ups Error 3.... Please check your data against!');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $datas = Merchant::select('*')->with('transaction', 'users')->where('id', $id)->first();
        $datas->transaction->status = ConvertStatusTransaction::f_status($datas->transaction->status);
        $status = StatusModel::all();
        return view('backend.transaction.edit', compact('status', 'datas'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $nominal = str_replace(".", "", str_replace("Rp. ", "", $request->nominal));
        $status = ConvertStatusTransaction::p_status($request->status);
        $transactionID = Transaction::where('merchantsId', $id)->pluck('id')->first();
        // dd($status);
        $this->validate($request, [
            'name' => 'required',
            'address' => 'required',
            'nominal' => 'required',
            'status' => 'required'
        ]);

        DB::beginTransaction();
        try {
            $data = Merchant::findorfail($id);
            $data->name = $request->name;
            $data->alamat = $request->address;
            $data->userId = Auth::user()->id;
            $data->save();

            if ($data) {
                $dataTransaction = Transaction::findorfail($transactionID);
                $dataTransaction->nominal = $nominal;
                $dataTransaction->merchantsId = $data->id;
                $dataTransaction->status = $status;
                $dataTransaction->date_transaction = $request->date;
                $dataTransaction->save();
                // dd($dataTransaction);

                DB::commit();
                return redirect()->route('transaction.index')->with('success', 'Data has been updated');

            } else {
                DB::rollBack();

                // echo "error 1";
                return redirect()->route('edit_transaction', $id)->with('error', 'Ups Error 1.... Please check your data against!');
            }
        } catch (Exception $e) {
            DB::rollBack();

            // dd("error 2 " . $e);
            return redirect()->route('edit_transaction', $id)->with('error', 'Ups Error 2... Please check your data against!');
        } catch (\Illuminate\Database\QueryException $e) {
            DB::rollBack();
            // dd("error 3 " . $e);
            return redirect()->route('edit_transaction', $id)->with('error', 'Ups Error 3.... Please check your data against!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        // dd($id);

        $transactionID = Transaction::where('merchantsId', $id)->pluck('id')->first();
        $data = Merchant::find($id)->delete();

        if ($data) {
            Transaction::findorfail($transactionID)->delete();
            return response()->json(array('success' => true));
        } else {
            return response()->json(array('error' => true));
        }
    }
}

03.laravel/resources/views/backend/transaction/create.blade.php
@extends('layout.backend')
@section('css')
<style>
.kotak {
    width: 350px;
    margin: auto;
    margin-top: 15px;
    padding: 10px;
}

p {
    margin-bottom: 20px;
    color: #0004ff;
}

input[type::number] {
    text-align: right;
    width: 100%;
    margin-bottom: 20px;
    margin-top: 10px;
    padding: 7px 10px;
    font-size: 18px;
}
</style>
@endsection
@section('content')


<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add Transaction</h1>
        <div cl ass="btn-toolbar mb-2 mb-md-0">
            <a href="{{route('transaction.index')}}" type="button" class="btn btn-sm btn-outline-secondary">
                <span data-feather="arrow-left"></span>

                Back
            </a>
        </div>
    </div>
    <div class="">
        <form method="post" action="{{route('transaction.store')}}">
            @csrf
            <div>
                @include('backend.transaction.form')
            </div>
        </form>
    </div>

</main>
@endsection
@section('script')
<script>
var rupiah = document.getElementById('nominalFloating');
rupiah.addEventListener('keyup', function(e) {
    // tambahkan 'Rp.' pada saat form di ketik
    // gunakan fungsi formatRupiah() untuk mengubah angka yang di ketik menjadi format angka
    rupiah.value = formatRupiah(this.value, 'Rp. ');

    /* Fungsi formatRupiah */
    function formatRupiah(angka, prefix) {
        var number_string = angka.replace(/[^,\d]/g, '').toString(),
            split = number_string.split(','),
            sisa = split[0].length % 3,
            rupiah = split[0].substr(0, sisa),
            ribuan = split[0].substr(sisa).match(/\d{3}/gi);

        // tambahkan titik jika yang di input sudah menjadi angka ribuan
        if (ribuan) {
            separator = sisa ? '.' : '';
            rupiah += separator + ribuan.join('.');
        }

        rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
        return prefix == undefined ? rupiah : (rupiah ? 'Rp. ' + rupiah : '');
    }
});
</script>
@endsection

03.laravel/resources/views/backend/transaction/edit.blade.php
@extends('layout.backend')
@section('css')
<style>
.kotak {
    width: 350px;
    margin: auto;
    margin-top: 15px;
    padding: 10px;
}

p {
    margin-bottom: 20px;
    color: #0004ff;
}

input[type::number] {
    text-align: right;
    width: 100%;
    margin-bottom: 20px;
    margin-top: 10px;
    padding: 7px 10px;
    font-size: 18px;
}
</style>
@endsection
@section('content')


<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Edit Transaction</h1>
        <div cl ass="btn-toolbar mb-2 mb-md-0">
            <a href="{{route('transaction.index')}}" type="button" class="btn btn-sm btn-outline-secondary">
                <span data-feather="arrow-left"></span>

                Back
            </a>
        </div>
    </div>
    <div class="">
        <form method="post" action="{{route('update_transaction',$datas->id)}}">
            @csrf
            @method('PATCH')
            <div>
                @include('backend.transaction.form')
            </div>
        </form>
    </div>

</main>
@endsection
@section('script')
<script>
var rupiah = document.getElementById('nominalFloating');
rupiah.addEventListener('keyup', function(e) {
    // tambahkan 'Rp.' pada saat form di ketik
    // gunakan fungsi formatRupiah() untuk mengubah angka yang di ketik menjadi format angka
    rupiah.value = formatRupiah(this.value, 'Rp. ');

    /* Fungsi formatRupiah */
    function formatRupiah(angka, prefix) {
        var number_string = angka.replace(/[^,\d]/g, '').toString(),
            split = number_string.split(','),
            sisa = split[0].length % 3,
            rupiah = split[0].substr(0, sisa),
            ribuan = split[0].substr(sisa).match(/\d{3}/gi);

        // tambahkan titik jika yang di input sudah menjadi angka ribuan
        if (ribuan) {
            separator = sisa ? '.' : '';
            rupiah += separator + ribuan.join('.');
        }

        rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
        return prefix == undefined ? rupiah : (rupiah ? 'Rp. ' + rupiah : '');
    }
});
</script>
@endsection

03.laravel/resources/views/backend/transaction/form.blade.php
@if(session()->has('error'))
{{session('error')}}
@enderror
<div class="row g-2">
    <div class="col-md">
        <div class="form-floating">
            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="floatingName"
                placeholder="Jhon Cena" required value="<?= isset($datas) == 0 ? old('name') : $datas->name?>">
            <label for="floatingName">Name</label>
        </div>
    </div>
    <div class="col-md">
        <div class="form-floating">
            <input type="text" step="0.01" class="form-control @error('nominal') is-invalid @enderror"
                id="nominalFloating" name="nominal" placeholder="Nominal"
                value="<?= isset($datas) == 0 ? old('name') : $datas->transaction->nominal?>">
            <label for="nominalFloating">Nominal</label>
            @error('nominal')
            <div class="invalid-feedback">
                Input Nominal
            </div>
            @enderror
        </div>
    </div>
</div>
</div>
<div class="row g-2 my-3">
    <div class="col-md">
        <div class="form-floating">
            <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea2"
                style="height: 100px" name="address"><?= isset($datas) == 0 ? old('name') : $datas->alamat?></textarea>
            <label for="floatingTextarea2">Address</label>
        </div>
        @error('address')
        <div class="invalid-feedback">
            Invalid Address
        </div>
        @enderror
    </div>

</div>
<div class="row g-2">
    <div class="col-md">
        <div class="form-floating">
            <input type="date" class="form-control  @error('date') is-invalid @enderror" id="dateFloating" name="date"
                value="<?= isset($datas) == 0 ? old('name') : $datas->transaction->date_transaction?>">
            <label for="dateFloating">Date</label>
            @error('date')
            <div class="invalid-feedback">
                input date.
            </div>
            @enderror
        </div>
    </div>
    <div class="col-md">
        <div class="form-floating">
            <select class="form-select" id="floatingSelectGrid" aria-label="Floating label select example" name="status"
                required>
                <option selected disabled>Select Status</option>
                @foreach($status as $value)
                <option value='{{$value["name"]}}' <?= isset($datas->transaction->status) ?
                $value->name == $datas->transaction->status ? 'selected' : '' : ''?>>{{$value->name}}</option>
                @endforeach
            </select>
            <label for="floatingSelectGrid">Status</label>
        </div>
    </div>
</div>
<div class="mt-3 d-flex justify-content-start align-items-start">
    <button class="btn btn-primary" type="submit"><i class="bi bi-save"></i> Save Data</button>
</div>

03.laravel/resources/views/backend/transaction/index.blade.php
@extends('layout.backend')
@section('content')

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">transaction Page</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{route('transaction.create')}}" type="button" class="btn btn-sm btn-secondary">
                <span data-feather="user-plus"></span>
                Add Data
            </a>
        </div>
    </div>

    <div class="container">
        @if(session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{session('success')}}
            <button class="btn-close" type="button" data-bs-dismiss="alert" arial-label="Close"></button>
        </div>
        @endif
        <table id="data-table" class="table display w-100">
            <thead class="text-center pt-4">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Alamat</th>
                    <th scope="col">Nominal</th>
                    <th scope="col">Status</th>
                    <th scope="col">Tanggal</th>
                    <!-- <th scope="col">Roles</th> -->
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>

</main>
@endsection
@section('script')
<script>
$(document).ready(function() {
    var table = $('#data-table').DataTable({
        stateSave: true,
        processing: true,
        serverSide: true,
        ordering: false,
        ajax: "{{ route('transaction.index') }}",
        columns: [{
                "data": "id",
                render: function(data, type, row, meta) {
                    return meta.row + meta.settings._iDisplayStart + 1;
                }
            },
            {
                data: 'name',
            },
            {
                data: 'alamat',
            },
            {
                data: 'transaction.nominal',
            },
            {
                data: 'transaction.status',
            },
            {
                data: 'transaction.date_transaction',
            },
            {
                data: 'action'
            }
        ]
    });
});

function deleteData(id) {
    let url = id;
    console.log(url);
    Swal.fire({
        title: 'Are you sure you want to delete this record?',
        text: 'If you delete this, it will be gone forever.',
        icon: 'warning',
        showCancelButton: true,
        showConfirmButton: true,
        buttonsStyling: true,
    }).then(function(e) {
        if (e.value === true) {
            $.ajax({
                type: "DELETE",
                url: `transaction/destroy/${url}`,
                data: {
                    "_token": "{{ csrf_token() }}",
                },
                success: function(data) {
                    if (data.success === true) {
                        Swal.fire('Deleted!', 'Delete Data Successfully!.', "success")
                        setTimeout(function() {
                            location.reload();
                        }, 2000);
                    } else {
                        swal.fire("Error!", 'Delete Data Failed', "error");
                    }
                }
            });
        } else {
            e.dismiss;
        }
    }, function(dismiss) {
        return false;
    });
}
</script>
@endsection