03.laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'LoginController@index')->name('login')->middleware('guest');

Route::post('authenticate', 'LoginController@loginForm')->name('Authenticate');
Route::post('logout', 'LoginController@logout')->name('logout');


Route::group(['middleware' => 'auth'], function () {
    Route::get('dashboard', 'Backend\DashboardController@index')->name('dashboard');
    // Route::resource('dashboard', 'Backend\DashboardController');

    Route::resource('users', 'Backend\UsersController');
    Route::get('users/edit/{id}', 'Backend\UsersController@show')->name('edit_users');
    Route::patch('users/update/{id}', 'Backend\UsersController@update')->name('update_users');
    Route::delete('users/destroy/{id}', 'Backend\UsersController@destroy')->name('destroy_users');

    Route::resource('transaction', 'Backend\TransactionController');
    Route::get('transaction/edit/{id}', 'Backend\TransactionController@show')->name('edit_transaction');
    Route::patch('transaction/update/{id}', 'Backend\TransactionController@update')->name('update_transaction');
    Route::delete('transaction/destroy/{id}', 'Backend\TransactionController@destroy')->name('destroy_transaction');


});

03.laravel/app/Models/User.php
<?php

namespace App\Models;

use App\Models\Entities\Model_has_Permissions;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    function model_has_role()
    {
        return $this->belongsTo(HasRoles::class);
    }
}

03.laravel/app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Helpers\ConvertStatusTransaction;
use App\Http\Controllers\Controller;
use App\Models\Entities\Merchant;
use App\Models\Entities\StatusModel;
use App\Models\Entities\Transaction;
use App\Models\User;
use Auth;
use Carbon\Carbon;
use DB;
use Illuminate\Database\Query\Builder;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Collection;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $users = Auth::user();

        $data['count_amount'] = $this->IDR(Transaction::sum('nominal'));
        $data['avg_amount'] = $this->IDR(Transaction::sum('nominal'));
        $status = StatusModel::all();
        $db_status2_sum = Transaction::select('status', DB::raw('SUM(nominal) as total'))->groupBY('status')->get();
        $db_status2_avg = Transaction::select('status', DB::raw('AVG(nominal) as avg'))->groupBY('status')->get();

        foreach ($status as $stts) {
            $stts->new_name = ConvertStatusTransaction::p_status($stts->name);
            foreach ($db_status2_sum as $item) {
                if ($stts->new_name == $item->status) {
                    $stts['total'] = $this->IDR($item->total);
                }
            }
            foreach ($db_status2_avg as $item) {
                if ($stts->new_name == $item->status) {
                    $stts['avg'] = $this->IDR($item->avg);
                }
            }

        }
        if ($request->ajax()) {

            $date = Carbon::now()->format('Y-m-d');
            $datas = Merchant::select('*')->with('transaction')->whereHas('transaction', function ($q) use ($date) {
                // Query the name field in status table
                $q->where('date_transaction', '=', $date); // '=' is optional
            })->get();
            return DataTables::of($datas)
                ->addIndexColumn()
                ->addColumn('user', function ($datas) {
                    $users = User::all();
                    foreach ($users as $user) {
                        if ($datas['userId'] == $user->id) {
                            $getName = $user->name;
                        }
                    }
                    return $getName;
                })
                ->addColumn('status', function ($datas) {
                    $newStatus = ConvertStatusTransaction::f_status($datas->transaction->status);
                    return $newStatus;
                })
                ->rawColumns(['user'])
                ->make(true);
        }

        return view('backend.dashboard.index', compact('users', 'data', 'status'));
    }

    private function IDR($angka)
    {
        $hasil_rupiah = "IDR " . number_format($angka, 0, ',', '.');
        return $hasil_rupiah;

    }
}

03.laravel/app/Http/Controllers/Backend/TransactionController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Helpers\ConvertStatusTransaction;
use App\Http\Controllers\Controller;
use App\Models\Entities\Merchant;
use App\Models\Entities\Transaction;
use App\Models\Entities\StatusModel;
use Auth;
use DB;
use Exception;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:transaction-list|transaction-create|transaction-edit|transaction-delete', ['only' => ['index', 'create', 'store', 'show', 'edit', 'update', 'destroy']]);
        $this->middleware('permission:transaction-create', ['only' => ['show', 'store']]);
        $this->middleware('permission:transaction-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:transaction-delete', ['only' => ['destroy']]);
    }
    public function index(Request $request)
    {
        //

        // dd($datas);
        if ($request->ajax()) {
            $datas = Merchant::select('*')->with('transaction', 'users')->where('userId', Auth::user()->id)->get();

            return DataTables::of($datas)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {

                    // Update Button
                    $updateButton = "<a href='" . route('edit_transaction', $row->id) . "' target='__blank' class='btn btn-sm btn-info updateUser' ><i class='bi bi-pencil-square'></i></a>";

                    // Delete Button
                    $deleteButton = "<a href='javascript:void(0);' class='btn btn-sm btn-danger deleteUser' onclick='deleteData(" . $row->id . ")'><i class='bi bi-trash'></i></a>";

                    return $updateButton . " " . $deleteButton;
                })
                ->rawColumns(['action'])
                ->make(true);

        }
        return view('backend.transaction.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $status = StatusModel::all();
        // dd($status);
        return view('backend.transaction.create', compact('status'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $nominal = str_replace(".", "", str_replace("Rp. ", "", $request->nominal));
        $status = ConvertStatusTransaction::p_status($request->status);
        // dd($status);
        $this->validate($request, [
            'name' => 'required',
            'address' => 'required',
            'nominal' => 'required',
            'status' => 'required'
        ]);

        DB::beginTransaction();
        try {
            $data = new Merchant;
            $data->name = $request->name;
            $data->alamat = $request->address;
            $data->userId = Auth::user()->id;
            $data->save();

            if ($data) {
                $dataTransaction = new Transaction;
                $dataTransaction->nominal = $nominal;
                $dataTransaction->merchantsId = $data->id;
                $dataTransaction->status = $status;
                $dataTransaction->date_transaction = $request->date;
                $dataTransaction->save();
                // dd($dataTransaction);

                DB::commit();
                return redirect()->route('transaction.index')->with('success', 'Data has been created');

            } else {
                DB::rollBack();

                // echo "error 1";
                return redirect()->route('transaction.create')->with('error', 'Ups Error 1.... Please check your data against!');
            }
        } catch (Exception $e) {
            DB::rollBack();

            // dd("error 2 " . $e);
            return redirect()->route('transaction.create')->with('error', 'Ups Error 2... Please check your data against!');
        } catch (\Illuminate\Database\QueryException $e) {
            DB::rollBack();
            // dd("error 3 " . $e);
            return redirect()->route('transaction.create')->with('error', 'Ups Error 3.... Please check your data against!');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $datas = Merchant::select('*')->with('transaction', 'users')->where('id', $id)->first();
        $datas->transaction->status = ConvertStatusTransaction::f_status($datas->transaction->status);
        $status = StatusModel::all();
        return view('backend.transaction.edit', compact('status', 'datas'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $nominal = str_replace(".", "", str_replace("Rp. ", "", $request->nominal));
        $status = ConvertStatusTransaction::p_status($request->status);
        $transactionID = Transaction::where('merchantsId', $id)->pluck('id')->first();
        // dd($status);
        $this->validate($request, [
            'name' => 'required',
            'address' => 'required',
            'nominal' => 'required',
            'status' => 'required'
        ]);

        DB::beginTransaction();
        try {
            $data = Merchant::findorfail($id);
            $data->name = $request->name;
            $data->alamat = $request->address;
            $data->userId = Auth::user()->id;
            $data->save();

            if ($data) {
                $dataTransaction = Transaction::findorfail($transactionID);
                $dataTransaction->nominal = $nominal;
                $dataTransaction->merchantsId = $data->id;
                $dataTransaction->status = $status;
                $dataTransaction->date_transaction = $request->date;
                $dataTransaction->save();
                // dd($dataTransaction);

                DB::commit();
                return redirect()->route('transaction.index')->with('success', 'Data has been updated');

            } else {
                DB::rollBack();

                // echo "error 1";
                return redirect()->route('edit_transaction', $id)->with('error', 'Ups Error 1.... Please check your data against!');
            }
        } catch (Exception $e) {
            DB::rollBack();

            // dd("error 2 " . $e);
            return redirect()->route('edit_transaction', $id)->with('error', 'Ups Error 2... Please check your data against!');
        } catch (\Illuminate\Database\QueryException $e) {
            DB::rollBack();
            // dd("error 3 " . $e);
            return redirect()->route('edit_transaction', $id)->with('error', 'Ups Error 3.... Please check your data against!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        // dd($id);

        $transactionID = Transaction::where('merchantsId', $id)->pluck('id')->first();
        $data = Merchant::find($id)->delete();

        if ($data) {
            Transaction::findorfail($transactionID)->delete();
            return response()->json(array('success' => true));
        } else {
            return response()->json(array('error' => true));
        }
    }
}

03.laravel/resources/views/backend/users/create.blade.php
@extends('layout.backend')
@section('content')


<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add User</h1>
        <div cl ass="btn-toolbar mb-2 mb-md-0">
            <a href="{{route('users.index')}}" type="button" class="btn btn-sm btn-outline-secondary">
                <span data-feather="arrow-left"></span>

                Back
            </a>
        </div>
    </div>
    <div class="">
        <form method="post" action="{{route('users.store')}}">
            @csrf
            <div>
                @include('backend.users.form')
            </div>
        </form>
    </div>

</main>
@endsection
@section('script')
<script>

</script>
@endsection

03.laravel/resources/views/backend/users/edit.blade.php
@extends('layout.backend')
@section('content')


<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Edit User</h1>
        <div cl ass="btn-toolbar mb-2 mb-md-0">
            <a href="{{route('users.index')}}" type="button" class="btn btn-sm btn-outline-secondary">
                <span data-feather="arrow-left"></span>

                Back
            </a>
        </div>
    </div>
    <div class="">
        <form method="post" action="{{route('update_users',$user->id)}}">
            @csrf
            @method('PATCH')
            <div>
                @include('backend.users.form')
            </div>
        </form>
    </div>

</main>
@endsection
@section('script')
<script>

</script>
@endsection

03.laravel/resources/views/backend/users/form.blade.php
<div class="row g-2">
    <div class="col-md">
        <div class="form-floating">
            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="floatingName"
                placeholder="Jhon Cena" required value="<?= isset($user) == 0 ? old('name') : $user['name']?>">
            <label for="floatingName">Name</label>
        </div>
    </div>
    <div class="col-md">
        <div class="form-floating">
            <input type="email" class="form-control @error('email') is-invalid @enderror" id="floatingEmail"
                placeholder="name@example.com" name="email" required
                value="<?= isset($user) == 0 ? old('email') : $user['email']?>">
            <label for="floatingEmail">Email address</label>
            @error('label')
            <div class="invalid-feedback">
                Invalid Email
            </div>
            @enderror
        </div>
    </div>
</div>
<div class="row g-2 my-3">
    <div class="col-md">
        <div class="form-floating">
            <input type="password" class="form-control @error('password') is-invalid @enderror" id="passwordFloating"
                name="password" placeholder="type your password">
            <label for="passwordFloating">Password</label>
            @error('password')
            <div class="invalid-feedback">
                Password do not match.
            </div>
            @enderror
        </div>
    </div>
    <div class="col-md">
        <div class="form-floating">
            <input type="password" class="form-control  @error('confirm_password') is-invalid @enderror"
                id="passwordFloating2" name="confirm_password" placeholder="Re-type your password">
            <label for="passwordFloating2">Confirm Password</label>
            @error('confirm_password')
            <div class="invalid-feedback">
                Password do not match.
            </div>
            @enderror
        </div>
    </div>
</div>
<div class="row g-2">
    <div class="col-md-3">
        <div class="form-floating">
            <select class="form-select" id="SelectRole" aria-label="Floating label select example" name="roles"
                required>
                <option selected disabled>Select Roles</option>
                @foreach($roles as $role)
                <option value='{{$role}}' <?= isset($userRole) ?
                $role == $userRole ? '' : 'selected' : ''?>>{{$role}}</option>
                @endforeach
            </select>
            <label for="SelectRole">Role</label>
        </div>
    </div>
</div>

<div class="mt-3 d-flex justify-content-end align-items-end">
    <button class="btn btn-primary" type="submit"><i class="bi bi-save"></i> Save Data</button>
</div>

03.laravel/resources/views/backend/users/index.blade.php
@extends('layout.backend')
@section('css')
<link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.5/dist/sweetalert2.min.css" rel="stylesheet">

@endsection
@section('content')

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">User Page</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{route('users.create')}}" type="button" class="btn btn-sm btn-secondary">
                <span data-feather="user-plus"></span>
                Add User
            </a>
        </div>
    </div>
    <div>
        @if(session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{session('success')}}
            <button class="btn-close" type="button" data-bs-dismiss="alert" arial-label="Close"></button>
        </div>
        @endif
        <table id="data-table" class="display w-100">
            <thead class="text-center pt-4">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <!-- <th scope="col">Roles</th> -->
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>

</main>
@endsection
@section('script')

<script>
$(document).ready(function() {
    var table = $('#data-table').DataTable({
        stateSave: true,
        processing: true,
        serverSide: true,
        ordering: false,
        ajax: "{{ route('users.index') }}",
        columns: [{
                "data": "id",
                render: function(data, type, row, meta) {
                    return meta.row + meta.settings._iDisplayStart + 1;
                }
            },
            {
                data: 'name',
            },
            {
                data: 'email',
            },
            {
                data: 'action'
            }
        ]
    });
});

function deleteData(id) {
    let url = id;
    console.log(url);
    Swal.fire({
        title: 'Are you sure you want to delete this record?',
        text: 'If you delete this, it will be gone forever.',
        icon: 'warning',
        showCancelButton: true,
        showConfirmButton: true,
        buttonsStyling: true,
    }).then(function(e) {
        if (e.value === true) {
            $.ajax({
                type: "DELETE",
                url: `users/destroy/${url}`,
                data: {
                    "_token": "{{ csrf_token() }}",
                },
                success: function(data) {
                    if (data.success === true) {
                        Swal.fire('Deleted!', 'Delete Data Successfully!.', "success")
                        setTimeout(function() {
                            location.reload();
                        }, 2000);
                    } else {
                        swal.fire("Error!", 'Delete Data Failed', "error");
                    }
                }
            });
        } else {
            e.dismiss;
        }
    }, function(dismiss) {
        return false;
    });
}
</script>
@endsection